server:
  port: 8181

web:
  #排除拦截的路由
  exclude-path-patterns: /, /admin/**, /favicon.ico, /swagger-resources/**, /swagger-ui/**, /webjars/**, /v3/**, /doc.html, /api/sys-user/login

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/mqr.db?date_string_format=yyyy-MM-dd HH:mm:ss
    username:
    password:

# 持久层配置
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.molicloud.mqr.entity,com.molicloud.mqr.plugin.*.entity
  global-config:
    # 关闭MP3.x自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
