-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 15:41:38 2020
-- Model: 茉莉QQ机器人数据库    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mqr
-- -----------------------------------------------------
-- 茉莉QQ机器人

-- -----------------------------------------------------
-- Schema mqr
--
-- 茉莉QQ机器人
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mqr` DEFAULT CHARACTER SET utf8mb4 ;
USE `mqr` ;

-- -----------------------------------------------------
-- Table `mqr`.`sys_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mqr`.`sys_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  `password` VARCHAR(200) NOT NULL COMMENT '密码',
  `salt` VARCHAR(100) NOT NULL COMMENT '盐',
  `avatar` VARCHAR(200) NOT NULL COMMENT '头像',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` BIT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0：正常，1：已删除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `mqr`.`sys_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mqr`.`sys_setting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '配置名',
  `value` TEXT NOT NULL COMMENT '配置值',
  `remark` VARCHAR(200) NOT NULL COMMENT '备注',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` BIT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0：正常，1：已删除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '配置表';


-- -----------------------------------------------------
-- Table `mqr`.`robot_group_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mqr`.`robot_group_member` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `gid` VARCHAR(50) NOT NULL COMMENT '群ID',
  `mid` VARCHAR(50) NOT NULL COMMENT '成员ID',
  `gold` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '金币',
  `hold_plugin` VARCHAR(100) NULL COMMENT '持有的插件',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` BIT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0：正常，1：已删除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '机器人群成员';


-- -----------------------------------------------------
-- Table `mqr`.`robot_friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mqr`.`robot_friend` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fid` VARCHAR(50) NOT NULL COMMENT '好友ID',
  `hold_plugin` VARCHAR(100) NULL COMMENT '持有的插件',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` BIT(1) NOT NULL DEFAULT 0 COMMENT '删除标记（0：正常，1：已删除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '机器人好友';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
